name: Build and Package
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build and Package
        run: |
          # Create required folders
          mkdir -p ./publish/Drivers
          mkdir -p ./publish/Docs
          
          # Build application
          dotnet publish ./src -c Release -r win-x64 --self-contained true -o ./publish
          
          # Copy drivers (if exist)
          if (Test-Path ./Drivers) { 
              cp ./Drivers/* ./publish/Drivers/
          } else {
              echo "⚠️ No Drivers folder found" > ./publish/Docs/WARNING.md
          }
          
          # Copy docs (if exist) or create minimal README
          if (Test-Path ./Docs) {
              cp ./Docs/* ./publish/Docs/
          } else {
              echo "# GE Ranger Programmer" > ./publish/Docs/README.md
              echo "Version: $(date +'%Y-%m-%d')" >> ./publish/Docs/README.md
          }
          
          # Create zip with everything
          7z a release.zip ./publish/*
          
          # Verify contents
          echo "=== Final Artifact Contents ==="
          tree ./publish
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: ./release.zip
