name: Production Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build App
        run: |
          dotnet publish ./src -c Release -r win-x64 -o ./publish
          
      - name: Package Files
        run: |
          mkdir dist
          cp -r ./publish/* ./dist/
          cp -r ./Drivers ./dist/
          
      - name: Create Final Zip
        run: |
          cd dist
          7z a ../GE-Ranger-Programmer.zip .
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
