name: Build (Win-x64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/GE-Ranger-Programmer.csproj -r win-x64

      - name: Build
        run: dotnet build src/GE-Ranger-Programmer.csproj -c Release -r win-x64 --no-restore

      - name: Publish
        run: dotnet publish src/GE-Ranger-Programmer.csproj -c Release -r win-x64 --no-build --no-restore

      - name: Package artifact (bin/src/docs/workflows)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path package | Out-Null

          # Bin: published output
          $pub = Join-Path -Path src -ChildPath 'bin\Release\net8.0-windows\win-x64\publish'
          if (Test-Path $pub) {
            Copy-Item -Recurse -Force $pub package\bin
          }

          # Drivers (if present) -> alongside bin
          if (Test-Path 'Drivers\inpoutx64.dll') {
            New-Item -ItemType Directory -Force -Path package\bin | Out-Null
            Copy-Item -Force 'Drivers\inpoutx64.dll' 'package\bin\inpoutx64.dll'
          }

          # Source: copy src minus bin/obj
          New-Item -ItemType Directory -Force -Path package\src | Out-Null
          & robocopy src package\src /E /XD bin obj .vs > $null

          # Docs (optional)
          if (Test-Path 'Docs') { Copy-Item -Recurse -Force Docs package\docs }
          elseif (Test-Path 'docs') { Copy-Item -Recurse -Force docs package\docs }

          # Workflows (requested)
          if (Test-Path '.github\workflows') {
            New-Item -ItemType Directory -Force -Path package\workflows | Out-Null
            Copy-Item -Recurse -Force '.github\workflows' 'package\workflows'
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer-win-x64
          path: package