name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Windows Forms Support
        run: |
          # Correct modern workload ID
          dotnet workload install wasm-tools
          dotnet workload install maui
          dotnet workload install maui-desktop

      - name: Build
        run: |
          dotnet restore ./src
          dotnet build ./src -c Release -r win-x64
          dotnet publish ./src -c Release -r win-x64 -o ./publish
          ls ./publish

      - name: Package
        run: |
          mkdir -p ./publish/Drivers
          mkdir -p ./publish/Docs
          cp -r ./Drivers/* ./publish/Drivers/ || echo "No drivers"
          cp -r ./Docs/* ./publish/Docs/ || echo "No docs"
          7z a artifact.zip ./publish/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Programmer
          path: artifact.zip
