name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Files
        run: |
          echo "=== Project File Contents ==="
          cat ./src/GE-Ranger-Programmer.csproj
          echo "=== Source Files ==="
          ls ./src/

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: |
          dotnet restore ./src
          dotnet publish ./src -c Release -r win-x64 -o ./publish
          
          echo "=== Build Output ==="
          ls ./publish

      - name: Package
        run: |
          mkdir -p ./publish/Drivers
          mkdir -p ./publish/Docs
          cp -r ./Drivers/* ./publish/Drivers/ || echo "No drivers found"
          cp -r ./Docs/* ./publish/Docs/ || echo "No docs found"
          7z a artifact.zip ./publish/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Programmer
          path: artifact.zip
