name: Production Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build application
        run: |
          # Build self-contained single file executable
          dotnet publish ./src -c Release -r win-x64 -o ./output `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:SelfContained=true `
            -p:RuntimeIdentifier=win-x64
          
      - name: Create flat distribution
        run: |
          # Create clean distribution folder
          mkdir dist
          
          # Copy ONLY the single executable
          cp ./output/GE-Ranger-Programmer.exe ./dist/
          
          # Copy drivers
          mkdir ./dist/Drivers
          cp ./Drivers/* ./dist/Drivers/
          
          # Create ZIP WITHOUT subfolders
          cd ./dist
          7z a -r ../GE-Ranger-Programmer.zip .
          
      - name: Verify artifact
        run: |
          echo "=== Artifact Contents ==="
          7z l GE-Ranger-Programmer.zip
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
