name: Production Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build application
        run: |
          dotnet publish ./src -c Release -r win-x64 -o ./output
          
      - name: Create distribution package
        run: |
          # Create clean dist folder
          mkdir dist
          
          # Copy executable and dependencies
          cp ./output/*.* ./dist/
          
          # Copy drivers
          mkdir ./dist/Drivers
          cp ./Drivers/* ./dist/Drivers/
          
          # Create flat zip
          cd ./dist
          7z a ../GE-Ranger-Programmer.zip *
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
