name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          dotnet publish ./src -c Release -r win-x64 -o ./publish
          
      - name: Create Raw Artifact
        run: |
          mkdir artifact
          cp -r ./publish/* ./artifact/
          cp -r ./Drivers ./artifact/
          
      - name: Upload Raw Files
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: ./artifact
