name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build Application
        run: |
          # Clean build
          dotnet clean
          dotnet publish ./src -c Release -r win-x64 -o ./publish --no-self-contained
          
          # Verify EXE exists
          if (!(Test-Path ./publish/GE-Ranger-Programmer.exe)) {
              echo "##[error] Executable not found!"
              exit 1
          }
      
      - name: Create Final Package
        run: |
          # Create clean output folder
          mkdir -p ./dist
          
          # Copy only necessary files
          cp ./publish/GE-Ranger-Programmer.exe ./dist/
          cp ./publish/*.dll ./dist/
          cp -r ./Drivers ./dist/
          
          # Create SINGLE zip
          cd ./dist
          7z a ../GE-Ranger-Programmer.zip *
          cd ..
          
          # Verify zip contents
          7z l GE-Ranger-Programmer.zip
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
