name: Production Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build Self-Contained App
        run: |
          dotnet publish ./src -c Release -r win-x64 -o ./output \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true
          
      - name: Package Release
        run: |
          # Create clean distribution folder
          mkdir dist
          
          # Copy main executable and drivers
          cp ./output/GE-Ranger-Programmer.exe ./dist/
          cp -r ./Drivers ./dist/
          
          # Create FLAT zip archive
          cd dist
          7z a ../GE-Ranger-Programmer.zip *
          
          # Verify zip contents
          echo "=== FINAL ZIP CONTENTS ==="
          7z l ../GE-Ranger-Programmer.zip
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
