name: Production Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src
      
      - name: Build application
        run: |
          dotnet publish ./src -c Release -r win-x64 -o ./publish
          echo "=== Publish directory contents ==="
          ls ./publish
      
      - name: Prepare distribution package
        run: |
          # Create clean distribution directory
          mkdir dist
          
          # Copy application files
          cp ./publish/GE-Ranger-Programmer.exe ./dist/
          cp ./publish/*.dll ./dist/ || echo "No DLLs copied"
          
          # Copy drivers
          mkdir ./dist/Drivers
          cp ./Drivers/* ./dist/Drivers/ || echo "No drivers copied"
          
          # Add documentation
          mkdir ./dist/Docs
          cp ./Docs/* ./dist/Docs/ || echo "No docs copied"
          
          # Create single zip archive
          cd ./dist
          7z a ../GE-Ranger-Programmer.zip *
          cd ..
          
          echo "=== Final ZIP contents ==="
          7z l GE-Ranger-Programmer.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GE-Ranger-Programmer
          path: GE-Ranger-Programmer.zip
