name: Build (Win-x64)

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (top level)
        shell: pwsh
        run: |
          Write-Host "=== REPO ROOT ==="
          Get-ChildItem -Force
          Write-Host "=== RECURSIVE (first 2 levels) ==="
          Get-ChildItem -Recurse -Depth 2 | Select-Object FullName

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: dotnet --info
        run: dotnet --info

      - name: Locate project
        id: locate
        shell: pwsh
        run: |
          $target = Get-ChildItem -Recurse -Filter GE-Ranger-Programmer.csproj | Select-Object -First 1
          if (-not $target) {
            $target = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          }
          if (-not $target) {
            Write-Error "No .csproj found in repository."
            exit 1
          }
          "csproj=$($target.FullName)" >> $env:GITHUB_OUTPUT
          "projdir=$($target.DirectoryName)" >> $env:GITHUB_OUTPUT
          Write-Host "Using project: $($target.FullName)"

      - name: Show project folder tree
        shell: pwsh
        run: |
          Write-Host "=== PROJECT DIR ==="
          Get-Child
