name: Gold Check (freq lock)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gold-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run gold frequency test
        run: dotnet run --project tests/GoldCheck/GoldCheck.csproj -c Release
